on:
  push:
    branches: master

env:
  VITE_ENV: ${{ secrets.VITE_ENV }}
  VITE_NEW_NIVEDOS_API: ${{ secrets.VITE_NEW_NIVEDOS_API }}
  VITE_ALL_CHANNEL_API: ${{ secrets.VITE_ALL_CHANNEL_API }}
  VITE_SINGLE_CHANNEL_API: ${{ secrets.VITE_SINGLE_CHANNEL_API }}
  VITE_RANDOM_FROM_CHANNEL_API: ${{ secrets.VITE_RANDOM_FROM_CHANNEL_API }}
  VITE_VIDEO_API: ${{ secrets.VITE_VIDEO_API }}
  VITE_MONGO_API: ${{ secrets.VITE_MONGO_API }}
  VITE_MONGO_NAME: ${{ secrets.VITE_MONGO_NAME }}
  VITE_MONGO_KEY: ${{ secrets.VITE_MONGO_KEY }}
  VITE_MONGO_LOGIN: ${{ secrets.VITE_MONGO_LOGIN }}
  VITE_MONGO_PASSWORD: ${{ secrets.VITE_MONGO_PASSWORD }}
  VITE_BACKEND: ${{ secrets.VITE_BACKEND }}

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm install --legacy-peer-deps
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: wn14.webd.pl
        username: github-automation@react.metalmusic.pl
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: 'dist/'