on:
  push:
    branches: master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run test
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: wn14.webd.pl
        username: github-automation@react.metalmusic.pl
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: 'dist/'